server:
 port: 3000
 
spring:
 jpa:
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: 
      org.hibernate.dialect.Oracle12cDialect
      
 datasource:
  url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB.localdomain
  username: root
  password: root